<a href="https://colab.research.google.com/github/ammigonz/bart/blob/main/DDR_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import lxml

In [ ]:
tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_San_Francisco_Designated_Landmarks')

In [ ]:
type(tables)

list

In [ ]:
len(tables)

3

In [ ]:
fares_table[2].dtypes

Station                                object
12th Street/ Oakland City Center       object
16th Street/ Mission                   object
19th Street Oakland                    object
24th Street/ Mission                   object
Antioch                                object
Ashby                                  object
Balboa Park                            object
Bay Fair                               object
Berryessa/ North San Jose              object
Castro Valley                          object
Civic Center/ UN Plaza                 object
Coliseum                               object
Colma                                  object
Concord                                object
Daly City                              object
Downtown Berkeley                      object
Dublin/ Pleasanton                     object
El Cerrito Del Norte                   object
El Cerrito Plaza                       object
Embarcadero                            object
Fremont                                object
Fruitvale                              object
Glen Park                              object
Hayward                                object
Lafayette                              object
Lake Merritt                           object
MacArthur                              object
Millbrae                               object
Milpitas                               object
Montgomery Street                      object
North Berkeley                         object
North Concord/ Martinez                object
Oakland International Airport          object
Orinda                                 object
Pittsburg Center                       object
Pittsburg/ Bay Point                   object
Pleasant Hill/ Contra Costa Centre     object
Powell Street                          object
Richmond                               object
Rockridge                              object
San Bruno                              object
San Francisco International Airport    object
San Leandro                            object
South Hayward                          object
South San Francisco                    object
Union City                             object
Walnut Creek                           object
Warm Springs/ South Fremont            object
West Dublin/ Pleasanton                object
West Oakland                           object
dtype: object

In [ ]:
tbl = tables[1]
tbl[:10]

,#,Name,Image,Address,Date designated,Description,Type
0,1,Mission Dolores,NaN,320 Dolores Street,"April 11, 1968",37°45′51″N 122°25′36″W﻿ / ﻿37.7642°N 122.4266°...,NRHP
1,2,Old Saint Mary's Cathedral,NaN,660 California Street,"April 11, 1968",37°47′34″N 122°24′21″W﻿ / ﻿37.79265°N 122.40575°W,CHISL
2,3,Bank of California Building,NaN,400 California Street,"September 3, 1968",37°47′36″N 122°24′06″W﻿ / ﻿37.7932°N 122.4016°...,SFDL
3,4,Saint Patrick's Church,NaN,756 Mission Street,"September 3, 1968",37°47′08″N 122°24′13″W﻿ / ﻿37.785588°N 122.403...,SFDL
4,5,Saint Francis of Assisi Church,NaN,610 Vallejo Street,"September 3, 1968",37°47′56″N 122°24′28″W﻿ / ﻿37.7988°N 122.4077°W,SFDL
5,6,Holy Cross Parish Hall (Old St. Patrick's Church),NaN,1820 Eddy Street,"September 3, 1968",37°46′51″N 122°26′16″W﻿ / ﻿37.7808°N 122.4378°W,SFDL
6,7,Audiffred Building,NaN,1–21 Mission Street,"October 13, 1968",37°47′36″N 122°23′33″W﻿ / ﻿37.7934°N 122.3926°...,NRHP
7,8,South San Francisco Opera House,NaN,1601 Newcomb Avenue,"December 8, 1968",37°44′07″N 122°23′24″W﻿ / ﻿37.735299°N 122.390...,NRHP
8,9,Belli Building (Langerman's Building),NaN,722 Montgomery Street,"February 3, 1969",37°47′46″N 122°24′12″W﻿ / ﻿37.7961°N 122.4033°...,SFDL
9,10,Genella Building (Belli Annex),NaN,728 Montgomery Street,"February 3, 1969",37°47′46″N 122°24′12″W﻿ / ﻿37.7961°N 122.4033°W,SFDL

In [ ]:
tbl = tables[1]
tbl[:10]

In [ ]:
fares_table = pd.read_html('https://www.transit.wiki/BART_fares')

In [ ]:
tbl = fares_table[2]
tbl[:10]

,Station,12th Street/ Oakland City Center,16th Street/ Mission,19th Street Oakland,24th Street/ Mission,Antioch,Ashby,Balboa Park,Bay Fair,Berryessa/ North San Jose,...,San Bruno,San Francisco International Airport,San Leandro,South Hayward,South San Francisco,Union City,Walnut Creek,Warm Springs/ South Fremont,West Dublin/ Pleasanton,West Oakland
0,12th Street/Oakland City Center,$7.10,$4.50,$2.40,$4.60,$6.90,$2.40,$5.10,$3.55,$7.25,...,$5.75,$11.50,$3.10,$4.45,$5.45,$5.05,$4.35,$6.05,$5.25,$2.40
1,16th Street/Mission,$4.50,$7.10,$4.50,$2.40,$9.20,$5.00,$2.40,$6.00,$9.45,...,$5.15,$11.05,$5.70,$6.70,$4.65,$7.30,$6.60,$8.25,$7.50,$4.30
2,19th Street Oakland,$2.40,$4.50,$7.10,$4.60,$6.90,$2.40,$5.10,$3.55,$7.25,...,$5.75,$11.50,$3.10,$4.45,$5.45,$5.05,$4.35,$6.05,$5.25,$2.40
3,24th Street/Mission,$4.60,$2.40,$4.60,$7.10,$9.25,$5.05,$2.40,$6.05,$9.50,...,$5.00,$10.90,$5.75,$6.75,$4.50,$7.35,$6.70,$8.30,$7.55,$4.40
4,Antioch,$6.90,$9.20,$6.90,$9.25,$7.10,$6.85,$9.50,$7.95,$11.45,...,$10.20,$15.95,$7.70,$8.70,$9.90,$9.30,$5.10,$10.25,$9.50,$7.05
5,Ashby,$2.40,$5.00,$2.40,$5.05,$6.85,$7.10,$5.35,$4.00,$7.50,...,$6.00,$11.75,$3.60,$4.75,$5.70,$5.35,$4.25,$6.30,$5.55,$2.40
6,Balboa Park,$5.10,$2.40,$5.10,$2.40,$9.50,$5.35,$7.10,$6.30,$9.80,...,$4.55,$10.45,$6.05,$7.00,$4.00,$7.65,$6.95,$8.60,$7.80,$4.90
7,Bay Fair,$3.55,$6.00,$3.55,$6.05,$7.95,$4.00,$6.30,$7.10,$6.00,...,$7.00,$12.75,$2.40,$2.40,$6.65,$2.40,$5.40,$4.80,$2.40,$3.75
8,Berryessa/North San Jose,$7.25,$9.45,$7.25,$9.50,$11.45,$7.50,$9.80,$6.00,$7.10,...,$10.45,$16.20,$6.30,$5.30,$10.15,$4.70,$8.90,$3.45,$7.50,$7.35
9,Castro Valley,$4.10,$6.30,$4.10,$6.40,$8.30,$4.35,$6.65,$2.40,$6.35,...,$7.35,$13.10,$2.40,$3.25,$7.00,$4.15,$5.75,$5.15,$2.40,$4.20

In [ ]:

from re import sub

In [ ]:
## Preprocessing
def remove(string):
    '''
    Removes everything inside [], a whitespace before that and *'s.
    '''
    if isinstance(string, str):
        string = sub(r'[,$]', '', string)
        flt = int(string)
    return flt

In [ ]:
def remove(string):
    '''
    Removes everything inside [], a whitespace before that and *'s.
    '''
    if isinstance(string, str):
        string = sub(r'[,$]', '', string)
        flt = float(string)  # Corrected to float
    return flt

In [ ]:
def convert_dollar_columns1(df):
    # Apply to all columns that contain dollar values
    for col in df.columns:
        if df[col].dtype == 'object':  # Only process string columns
            # Check if the column contains dollar signs
            if df[col].str.contains('\$').any():
                # First remove dollar sign, commas, and convert to float
                df[col] = df[col].apply(lambda x: (float(sub(r'[$,]', '', x))) if isinstance(x, str) else x)
    return df

In [ ]:
def convert_dollar_columns(df):
    # Apply to all columns that contain dollar values
    for col in df.columns:
        if df[col].dtype == 'object':  # Only process string columns
            # Check if the column contains dollar signs
            if df[col].str.contains('\$').any():
                # First remove dollar sign, convert to float, preserve decimals
                df[col] = df[col].apply(lambda x: float(sub(r'[,$]', '', x.strip())))                # Ensure the column type is explicitly float
                df[col] = df[col].astype(float)
    return df

In [ ]:
def convert_dollar_columns(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            if df[col].str.contains('\$').any():
                df[col] = df[col].apply(lambda x: convert_to_float(x))
                df[col] = df[col].astype(float)
    return df

def convert_to_float(x):
    try:
        return float(sub(r'[,$]', '', x.strip()))
    except ValueError:
        # Handle cases where conversion fails (e.g., empty string or invalid characters)
        return float('nan')  # Replace with NaN or other desired default value

In [ ]:
def remove_dollar_signs(df):
    # Create a copy to avoid modifying the original DataFrame
    df_copy = df.copy()
    # Apply to all columns that contain dollar values
    for col in df_copy.columns:
        if df_copy[col].dtype == 'object':  # Only process string columns
            # Check if the column contains dollar signs
            if df_copy[col].str.contains('\$').any():
                # Just remove the dollar sign, keep as string
                df_copy[col] = df_copy[col].str.replace('\$', '', regex=True)
    return df_copy

In [ ]:
convert_to_float(tbl)

AttributeError: 'DataFrame' object has no attribute 'strip'

In [ ]:
remove_dollar_signs(tbl)

,Station,12th Street/ Oakland City Center,16th Street/ Mission,19th Street Oakland,24th Street/ Mission,Antioch,Ashby,Balboa Park,Bay Fair,Berryessa/ North San Jose,...,San Bruno,San Francisco International Airport,San Leandro,South Hayward,South San Francisco,Union City,Walnut Creek,Warm Springs/ South Fremont,West Dublin/ Pleasanton,West Oakland
0,12th Street/Oakland City Center,7,4,2,4,6,2,5,3,7,...,5,11,3,4,5,5,4,6,5,2
1,16th Street/Mission,4,7,4,2,9,5,2,6,9,...,5,11,5,6,4,7,6,8,7,4
2,19th Street Oakland,2,4,7,4,6,2,5,3,7,...,5,11,3,4,5,5,4,6,5,2
3,24th Street/Mission,4,2,4,7,9,5,2,6,9,...,5,10,5,6,4,7,6,8,7,4
4,Antioch,6,9,6,9,7,6,9,7,11,...,10,15,7,8,9,9,5,10,9,7
5,Ashby,2,5,2,5,6,7,5,4,7,...,6,11,3,4,5,5,4,6,5,2
6,Balboa Park,5,2,5,2,9,5,7,6,9,...,4,10,6,7,4,7,6,8,7,4
7,Bay Fair,3,6,3,6,7,4,6,7,6,...,7,12,2,2,6,2,5,4,2,3
8,Berryessa/North San Jose,7,9,7,9,11,7,9,6,7,...,10,16,6,5,10,4,8,3,7,7
9,Castro Valley,4,6,4,6,8,4,6,2,6,...,7,13,2,3,7,4,5,5,2,4
10,Civic Center/UN Plaza,4,2,4,2,9,4,2,5,9,...,5,11,5,6,4,7,6,8,7,3
11,Coliseum,2,5,2,5,7,3,5,2,6,...,6,12,2,3,6,4,4,5,4,2
12,Colma,5,4,5,4,9,5,4,6,9,...,4,9,6,7,4,7,7,8,7,5
13,Concord,5,7,5,7,4,5,7,6,9,...,8,14,5,6,8,7,2,8,7,5
14,Daly City,5,3,5,3,9,5,3,6,9,...,4,10,6,7,4,7,7,8,8,5
15,Downtown Berkeley,2,5,2,5,6,2,5,4,7,...,6,11,3,4,5,5,4,6,5,2
16,Dublin/Pleasanton,5,7,5,7,9,5,8,2,7,...,8,14,4,4,8,5,7,6,2,5
17,El Cerrito Del Norte,3,5,3,5,7,2,5,4,8,...,6,12,4,5,6,5,4,6,6,3
18,El Cerrito Plaza,2,5,2,5,7,2,5,4,7,...,6,12,4,5,6,5,4,6,5,3
19,Embarcadero,4,2,4,2,9,4,2,5,9,...,5,11,5,6,4,7,6,8,7,3
20,Fremont,5,7,5,7,9,5,8,2,4,...,8,14,4,2,8,2,7,2,5,5
21,Fruitvale,2,5,2,5,7,2,5,3,6,...,6,11,2,4,5,4,4,5,4,2
22,Glen Park,4,2,4,2,9,5,2,6,9,...,4,10,5,6,4,7,6,8,7,4
23,Hayward,4,6,4,6,8,4,6,2,5,...,7,13,2,2,7,2,5,4,4,4
24,Lafayette,3,6,3,6,5,3,6,4,8,...,7,12,4,5,6,6,2,7,6,4
25,Lake Merritt,2,4,2,4,6,2,5,3,7,...,5,11,3,4,5,5,4,6,5,2
26,MacArthur,2,4,2,4,6,2,5,3,7,...,5,11,3,4,5,5,4,6,5,2
27,Millbrae,6,5,6,5,10,6,5,7,10,...,4,5,7,8,4,8,8,9,8,6
28,Milpitas,6,9,6,9,11,7,9,5,2,...,10,15,6,5,9,4,8,2,7,7
29,Montgomery Street,4,2,4,2,9,4,2,5,9,...,5,11,5,6,4,7,6,8,7,3
30,North Berkeley,2,5,2,5,6,2,5,4,7,...,6,11,3,4,5,5,4,6,5,2
31,North Concord/Martinez,5,7,5,7,4,5,7,6,9,...,8,14,6,7,8,7,2,8,7,5
32,Oakland International Airport,9,12,9,12,14,10,13,9,14,...,13,19,9,11,13,12,12,12,12,10
33,Orinda,3,5,3,5,6,2,6,4,7,...,6,12,4,5,6,5,2,6,6,3
34,Pittsburg Center,6,8,6,8,2,6,8,7,10,...,9,15,6,7,9,8,4,9,8,6
35,Pittsburg/Bay Point,5,8,5,8,2,5,8,7,10,...,9,14,6,7,8,8,2,9,8,6
36,Pleasant Hill/Contra Costa Centre,4,6,4,6,4,4,7,5,9,...,7,13,5,6,7,6,2,7,7,4
37,Powell Street,4,2,4,2,9,4,2,5,9,...,5,11,5,6,4,7,6,8,7,3
38,Richmond,3,5,3,5,7,2,6,4,8,...,6,12,4,5,6,6,5,7,6,3
39,Rockridge,2,5,2,5,6,2,5,3,7,...,6,11,3,4,5,5,4,6,5,2
40,San Bruno,5,5,5,5,10,6,4,7,10,...,7,9,6,7,4,8,7,9,8,5
41,San Francisco International Airport,11,11,11,10,15,11,10,12,16,...,9,7,12,13,9,14,13,15,14,11
42,San Leandro,3,5,3,5,7,3,6,2,6,...,6,12,7,3,6,4,5,5,4,3
43,South Hayward,4,6,4,6,8,4,7,2,5,...,7,13,3,7,7,2,6,2,4,4
44,South San Francisco,5,4,5,4,9,5,4,6,10,...,4,9,6,7,7,8,7,8,8,5
45,Union City,5,7,5,7,9,5,7,2,4,...,8,14,4,2,8,7,6,2,5,5
46,Walnut Creek,4,6,4,6,5,4,6,5,8,...,7,13,5,6,7,6,7,7,6,4
47,Warm Springs/South Fremont,6,8,6,8,10,6,8,4,3,...,9,15,5,2,8,2,7,7,6,6
48,West Dublin/Pleasanton,5,7,5,7,9,5,7,2,7,...,8,14,4,4,8,5,6,6,7,5
49,West Oakland,2,4,2,4,7,2,4,3,7,...,5,11,3,4,5,5,4,6,5,7

In [ ]:
for column in tbl.columns:
    tbl[column] = tbl[column].apply(remove)
    #fares_table[column] = tbl[column].str.replace('$', '')

ValueError: invalid literal for int() with base 10: '12th Street/Oakland City Center'

In [ ]:
sortbycost = tbl.sort_values(by=[tbl.columns[4]], ascending=False)
sortbycost[:10]